name: Build LaTeX document
on:
  push:
    branches: [ "main" ]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: liste-des-rumtreibers.tex
          latexmk_use_xelatex: true
          
      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: liste-des-rumtreibers
          path: liste-des-rumtreibers.pdf
